[package]
name = "nice-game"
version = "0.1.0"
authors = ["IcyDefiance <icydefiance@gmail.com>"]

[dependencies]
atom = "0.3"
futures = "0.2"
image = "0.19"
lazy_static = "1.0"
num_cpus = "1.8"
vulkano = "0.9"
vulkano-shader-derive = "0.9"
vulkano-win = "0.9"
winit = "0.11"

[workspace]
members = [
	"examples/sprite",
	"examples/target_texture"
]
