[package]
name = "nice-game"
version = "0.1.0"
authors = ["IcyDefiance <icydefiance@gmail.com>"]

[dependencies]
vulkano = "0.9"
vulkano-shader-derive = "0.9"
vulkano-win = "0.9"
winit = "0.11"

[workspace]
members = [
	"examples/triangle"
]
