[package]
name = "mesh"
version = "0.1.0"
authors = ["IcyDefiance <icydefiance@gmail.com>"]

[profile.release]
lto = true

[dependencies]
cgmath = "0.16"
futures = "0.2"
nice-game = { path = "../../" }
simplelog = "0.5"
